spring:
  datasource:
    url: jdbc:mysql://db:3306/localDB?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update